apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name}}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      run: {{ .Values.run }}
  template:
    metadata:
      labels:
        run: {{ .Values.run }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
          - containerPort: {{ .Values.service.port }}

   
